-- Unified payment layer (v2.42.0-data) — behavior-neutral spine.
--
-- Every paid service (1UP Pass, paid tournaments, $1UP purchases, academia
-- courses; marketplace later) will record its payments as rows in a single
-- `payment_events` ledger, polymorphically linked to the owning order via
-- (order_kind, order_id) — NO foreign key, same precedent as
-- enrollments.product_type. The existing per-service order tables keep their
-- own audited state machines; this layer plugs in alongside them.
--
-- Nothing reads/writes these objects yet — the routes adopt them in v2.42.0.
-- Decisions locked after a security audit:
--   * Consistency lives in the DB: apply_payment_event() serializes concurrent
--     callers (transaction-scoped advisory lock) and enforces the v1
--     single-payment invariant, returning `became_paid` true for EXACTLY one
--     caller. Fulfillment fires iff became_paid — closing the double-fulfillment
--     race the JS-side design would have re-opened.
--   * v1 fulfills only on a single FULL payment (no deposits) → at most one
--     confirmed event per order. Deposits/SUM-math land later WITH a reservation
--     lifecycle + reconciliation panel.
--   * Legacy payment_method='bank' values are NOT renamed; 'wire' is the new
--     canonical name, bridged in code (methodRegistry.ts).
--   * card (Stripe) is reserved-only here: the stripe_* columns + card_enabled
--     flag exist, but no webhook route ships until card goes live.

-- 1) Enums -------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE public.payment_method AS ENUM ('token', 'wire', 'cash', 'card');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE public.payment_event_status AS ENUM ('pending', 'confirmed', 'rejected', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE TYPE public.order_kind AS ENUM ('pass', 'tournament_entry', 'token_purchase', 'enrollment');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 2) Ledger ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_events (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_kind               public.order_kind         NOT NULL,
  order_id                 bigint                    NOT NULL,
  method                   public.payment_method     NOT NULL,
  -- Exactly one denominating unit per event (matches the chosen method).
  amount_cop               integer,
  amount_tokens            numeric(20, 4),
  status                   public.payment_event_status NOT NULL DEFAULT 'pending',
  -- method-specific references (all nullable)
  tx_hash                  text,
  block_number             bigint,
  wallet_address           text,
  bank_account_id          integer REFERENCES public.bank_accounts(id),
  comprobante_url          text,
  recorded_by_admin        text,
  reason                   text,
  idempotency_key          text,
  -- reserved for card (Stripe) — populated only once card goes live
  stripe_payment_intent_id   text,
  stripe_checkout_session_id text,
  -- audit
  rejection_reason         text,
  reviewed_by              text,
  reviewed_at              timestamptz,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payment_events_one_unit CHECK (
    (amount_cop IS NOT NULL AND amount_tokens IS NULL) OR
    (amount_cop IS NULL AND amount_tokens IS NOT NULL)
  ),
  CONSTRAINT payment_events_amount_positive CHECK (
    (amount_cop    IS NULL OR amount_cop    > 0) AND
    (amount_tokens IS NULL OR amount_tokens > 0)
  ),
  -- cash is admin-attested: it must carry who recorded it and why.
  CONSTRAINT payment_events_cash_audited CHECK (
    method <> 'cash' OR (recorded_by_admin IS NOT NULL AND reason IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS payment_events_order_idx
  ON public.payment_events (order_kind, order_id);

CREATE INDEX IF NOT EXISTS payment_events_status_idx
  ON public.payment_events (status);

-- On-chain replay block — GLOBAL across all order kinds: one tx can back one
-- event, period (mirrors the per-table tx_hash unique indexes it generalizes).
CREATE UNIQUE INDEX IF NOT EXISTS payment_events_tx_hash_uniq
  ON public.payment_events (lower(tx_hash)) WHERE tx_hash IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS payment_events_stripe_pi_uniq
  ON public.payment_events (stripe_payment_intent_id) WHERE stripe_payment_intent_id IS NOT NULL;

-- 3) Per-service enabled-methods config (admin-editable) ----------------------
CREATE TABLE IF NOT EXISTS public.service_payment_methods (
  service        public.order_kind PRIMARY KEY,
  token_enabled  boolean NOT NULL DEFAULT true,
  wire_enabled   boolean NOT NULL DEFAULT true,
  cash_enabled   boolean NOT NULL DEFAULT false,
  card_enabled   boolean NOT NULL DEFAULT false,
  updated_by     text,
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- Seed one row per service with defaults matching today's live behavior
-- (token + wire on; cash/card off). Idempotent.
INSERT INTO public.service_payment_methods (service)
VALUES ('pass'), ('tournament_entry'), ('token_purchase'), ('enrollment')
ON CONFLICT (service) DO NOTHING;

-- 4) The atomic cornerstone --------------------------------------------------
-- Records a CONFIRMED payment against an order — either by confirming an
-- existing pending event (wire approval) or inserting a new confirmed event
-- (token success, cash). Serializes concurrent callers on the same logical
-- order and enforces the v1 single-confirmed invariant, returning `became_paid`
-- true for exactly one caller. Amount-correctness is the caller's job (token =
-- on-chain exact-match verify; cash/wire = fixed price) — this function owns the
-- race/idempotency guarantee only.
CREATE OR REPLACE FUNCTION public.apply_payment_event(
  p_order_kind        public.order_kind,
  p_order_id          bigint,
  p_event_id          bigint                 DEFAULT NULL,
  p_method            public.payment_method  DEFAULT NULL,
  p_amount_cop        integer                DEFAULT NULL,
  p_amount_tokens     numeric                DEFAULT NULL,
  p_tx_hash           text                   DEFAULT NULL,
  p_block_number      bigint                 DEFAULT NULL,
  p_wallet_address    text                   DEFAULT NULL,
  p_bank_account_id   integer                DEFAULT NULL,
  p_comprobante_url   text                   DEFAULT NULL,
  p_recorded_by_admin text                   DEFAULT NULL,
  p_reason            text                   DEFAULT NULL,
  p_idempotency_key   text                   DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  existing_confirmed int;
  ev                 public.payment_events%ROWTYPE;
  new_id             bigint;
BEGIN
  -- Transaction-scoped lock keyed on the logical order. Auto-released at
  -- COMMIT/ROLLBACK; serializes confirmations without coupling this function
  -- to any specific parent table.
  PERFORM pg_advisory_xact_lock(
    hashtextextended(p_order_kind::text || ':' || p_order_id::text, 0)
  );

  -- v1 single-payment invariant: at most one confirmed event per order.
  SELECT count(*) INTO existing_confirmed
  FROM payment_events
  WHERE order_kind = p_order_kind AND order_id = p_order_id AND status = 'confirmed';

  IF existing_confirmed > 0 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'already_paid', 'became_paid', false);
  END IF;

  IF p_event_id IS NOT NULL THEN
    -- Confirm an existing pending event (e.g. admin approves a wire).
    SELECT * INTO ev FROM payment_events WHERE id = p_event_id FOR UPDATE;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('ok', false, 'reason', 'not_found', 'became_paid', false);
    END IF;
    IF ev.order_kind <> p_order_kind OR ev.order_id <> p_order_id THEN
      RETURN jsonb_build_object('ok', false, 'reason', 'order_mismatch', 'became_paid', false);
    END IF;
    IF ev.status <> 'pending' THEN
      RETURN jsonb_build_object('ok', false, 'reason', 'not_pending', 'became_paid', false);
    END IF;

    UPDATE payment_events
       SET status = 'confirmed', reviewed_by = p_recorded_by_admin, reviewed_at = now(), updated_at = now()
     WHERE id = p_event_id;

    RETURN jsonb_build_object('ok', true, 'event_id', p_event_id, 'became_paid', true);
  END IF;

  -- Insert a brand-new confirmed event (token success, cash).
  BEGIN
    INSERT INTO payment_events (
      order_kind, order_id, method, amount_cop, amount_tokens, status,
      tx_hash, block_number, wallet_address, bank_account_id, comprobante_url,
      recorded_by_admin, reason, idempotency_key
    ) VALUES (
      p_order_kind, p_order_id, p_method, p_amount_cop, p_amount_tokens, 'confirmed',
      p_tx_hash, p_block_number, p_wallet_address, p_bank_account_id, p_comprobante_url,
      p_recorded_by_admin, p_reason, p_idempotency_key
    ) RETURNING id INTO new_id;
  EXCEPTION WHEN unique_violation THEN
    -- tx already claimed by another event (replay) or duplicate stripe intent.
    RETURN jsonb_build_object('ok', false, 'reason', 'duplicate', 'became_paid', false);
  END;

  RETURN jsonb_build_object('ok', true, 'event_id', new_id, 'became_paid', true);
END;
$function$;
