-- v2.41.0 — paid tournament entry (Option A: dedicated entry-orders table).
--
-- A tournament can charge a registration fee in $1UP and/or COP (null = free,
-- unchanged behavior). Payment is recorded in `tournament_entry_orders`, mirroring
-- the pass/token order pattern (token = on-chain verify; bank = comprobante + admin
-- approve). A registration is created (and counts toward capacity) ONLY when an
-- entry order is confirmed — capacity is enforced by the existing
-- `register_for_tournament` RPC at confirmation time. No refunds in v1.

-- ── 1. Fee columns on tournaments ───────────────────────────────────
ALTER TABLE public.tournaments
  ADD COLUMN IF NOT EXISTS entry_fee_tokens numeric NULL,
  ADD COLUMN IF NOT EXISTS entry_fee_cop    integer NULL;

-- ── 2. Entry-order status enum ──────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE public.tournament_entry_status AS ENUM ('pending_bank', 'confirmed', 'rejected', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ── 3. tournament_entry_orders (the payment record) ─────────────────
CREATE TABLE IF NOT EXISTS public.tournament_entry_orders (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id   bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  user_profile_id bigint NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  privy_user_id   text NOT NULL,
  registration_id bigint REFERENCES public.tournament_registrations(id) ON DELETE SET NULL,
  payment_method  text NOT NULL CHECK (payment_method IN ('token', 'bank')),
  amount_tokens   numeric NULL,
  amount_cop      integer NULL,
  wallet_address  text NULL,
  tx_hash         text NULL,
  block_number    bigint NULL,
  bank_account_id integer NULL REFERENCES public.bank_accounts(id),
  comprobante_url text NULL,
  status          public.tournament_entry_status NOT NULL DEFAULT 'pending_bank',
  rejection_reason text NULL,
  reviewed_by     text NULL,
  reviewed_at     timestamptz NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- One in-flight (pending/confirmed) entry order per user per tournament.
CREATE UNIQUE INDEX IF NOT EXISTS tournament_entry_orders_one_active_per_user
  ON public.tournament_entry_orders (tournament_id, user_profile_id)
  WHERE status IN ('pending_bank', 'confirmed');

-- tx_hash idempotency for the token path (same pattern as pass_orders/enrollments).
CREATE UNIQUE INDEX IF NOT EXISTS tournament_entry_orders_tx_hash_uniq
  ON public.tournament_entry_orders (lower(tx_hash))
  WHERE tx_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS tournament_entry_orders_status_idx     ON public.tournament_entry_orders (status);
CREATE INDEX IF NOT EXISTS tournament_entry_orders_tournament_idx ON public.tournament_entry_orders (tournament_id);

-- RLS off — all access via supabaseAdmin at the API layer (matches pass_orders).
