-- v2.38.0 — 1UP Pass as a first-class, activatable object (Phase 1, off-chain, NFT-ready)
--
-- Introduces a `passes` table: one row per pass *asset* (vs `pass_orders`, which
-- stays as the *transaction* record — how the pass was acquired). The `passes.id`
-- is the future ERC-721 tokenId. This migration is BEHAVIOR-NEUTRAL: newly
-- confirmed orders are mirrored into `passes` as `active` exactly like today, and
-- `user_profiles.pass_status` is now derived from `passes` instead of `pass_orders`.
-- Claim-later activation + the "Activar" UI land in Phase 2 (no app changes here).

-- ── 1. pass_state enum ──────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE public.pass_state AS ENUM ('issued', 'active', 'expired', 'revoked');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ── 2. passes table (the asset) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.passes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_profile_id bigint NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  owner_wallet_address  text,
  source                text NOT NULL CHECK (source IN ('purchase', 'admin_grant', 'tournament_prize')),
  source_order_id       bigint REFERENCES public.pass_orders(id) ON DELETE SET NULL,
  source_ref            text,                 -- provenance (e.g. tournament name / results id)
  duration_days         integer NOT NULL CHECK (duration_days > 0),
  state                 public.pass_state NOT NULL DEFAULT 'issued',
  activated_at          timestamptz,          -- null until the holder activates (claim-later)
  expires_at            timestamptz,          -- null until activation, then activated_at + duration
  issued_at             timestamptz NOT NULL DEFAULT now(),
  issued_by             text,
  revoked_at            timestamptz,
  revoked_by            text,
  revoke_reason         text,
  -- Phase 2 (NFT on Base) — null until minted
  token_id              numeric,
  contract_address      text,
  mint_tx_hash          text,
  chain_id              integer,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT passes_source_order_id_uniq UNIQUE (source_order_id),
  CONSTRAINT passes_state_consistency CHECK (
    (state = 'issued'  AND activated_at IS NULL     AND expires_at IS NULL     AND revoked_at IS NULL) OR
    (state = 'active'  AND activated_at IS NOT NULL AND expires_at IS NOT NULL AND revoked_at IS NULL) OR
    (state = 'expired' AND activated_at IS NOT NULL AND expires_at IS NOT NULL AND revoked_at IS NULL) OR
    (state = 'revoked' AND revoked_at IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS passes_owner_idx        ON public.passes (owner_user_profile_id);
CREATE INDEX IF NOT EXISTS passes_state_idx        ON public.passes (state);
CREATE INDEX IF NOT EXISTS passes_owner_active_idx ON public.passes (owner_user_profile_id) WHERE state = 'active';

-- ── 3. Derive user_profiles.pass_status from passes ─────────────────
CREATE OR REPLACE FUNCTION public.recompute_pass_status(p_uid bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  UPDATE user_profiles SET pass_status = CASE
    WHEN EXISTS (SELECT 1 FROM passes WHERE owner_user_profile_id = p_uid AND state = 'active' AND expires_at > now())
      THEN 'active'::pass_status_enum
    WHEN EXISTS (SELECT 1 FROM passes WHERE owner_user_profile_id = p_uid AND state IN ('active', 'expired'))
      THEN 'expired'::pass_status_enum
    ELSE 'never'::pass_status_enum
  END
  WHERE id = p_uid;
END; $$;

CREATE OR REPLACE FUNCTION public.passes_sync_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  PERFORM recompute_pass_status(COALESCE(NEW.owner_user_profile_id, OLD.owner_user_profile_id));
  -- transfer (PR3): if ownership moved, refresh the prior owner too
  IF TG_OP = 'UPDATE' AND NEW.owner_user_profile_id <> OLD.owner_user_profile_id THEN
    PERFORM recompute_pass_status(OLD.owner_user_profile_id);
  END IF;
  RETURN NULL;
END; $$;

DROP TRIGGER IF EXISTS trg_passes_sync_status ON public.passes;
CREATE TRIGGER trg_passes_sync_status
AFTER INSERT OR UPDATE OR DELETE ON public.passes
FOR EACH ROW EXECUTE FUNCTION public.passes_sync_status();

-- ── 4. Backfill existing confirmed orders into passes ───────────────
-- 22 confirmed orders → 21 active + 1 expired. Preserves every active user.
INSERT INTO public.passes (
  owner_user_profile_id, owner_wallet_address, source, source_order_id,
  duration_days, state, activated_at, expires_at, issued_by, issued_at
)
SELECT
  po.user_profile_id, po.wallet_address,
  CASE po.payment_method WHEN 'admin_grant' THEN 'admin_grant' ELSE 'purchase' END,
  po.id, po.duration_days,
  CASE WHEN po.expires_at > now() THEN 'active' ELSE 'expired' END::public.pass_state,
  COALESCE(po.started_at, po.paid_at, po.created_at), po.expires_at,
  COALESCE(po.granted_by, po.reviewed_by, 'system'), COALESCE(po.paid_at, po.created_at)
FROM public.pass_orders po
WHERE po.status = 'confirmed' AND po.expires_at IS NOT NULL
ON CONFLICT (source_order_id) DO NOTHING;

-- ── 5. Repoint the pass_orders trigger to mirror into passes ────────
-- Keeps every existing purchase/grant code path working with ZERO app changes:
-- a confirmed order auto-creates an active pass; the passes trigger then syncs
-- pass_status. The `WHERE passes.state IN ('active','expired')` guard prevents a
-- later order edit from clobbering a manually revoked or claim-later (issued) pass.
CREATE OR REPLACE FUNCTION public.sync_user_pass_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN
  IF NEW.status = 'confirmed' AND NEW.expires_at IS NOT NULL THEN
    INSERT INTO passes (
      owner_user_profile_id, owner_wallet_address, source, source_order_id,
      duration_days, state, activated_at, expires_at, issued_by, issued_at
    ) VALUES (
      NEW.user_profile_id, NEW.wallet_address,
      CASE NEW.payment_method WHEN 'admin_grant' THEN 'admin_grant' ELSE 'purchase' END,
      NEW.id, NEW.duration_days,
      CASE WHEN NEW.expires_at > now() THEN 'active' ELSE 'expired' END::pass_state,
      COALESCE(NEW.started_at, NEW.paid_at, NEW.created_at), NEW.expires_at,
      COALESCE(NEW.granted_by, NEW.reviewed_by, 'system'), now()
    )
    ON CONFLICT (source_order_id) DO UPDATE SET
      expires_at    = EXCLUDED.expires_at,
      activated_at  = EXCLUDED.activated_at,
      duration_days = EXCLUDED.duration_days,
      state         = CASE WHEN EXCLUDED.expires_at > now() THEN 'active' ELSE 'expired' END::pass_state,
      updated_at    = now()
    WHERE passes.state IN ('active', 'expired');
  END IF;
  RETURN NEW;
END; $$;

-- ── 6. Nightly cron now expires passes (cascades to pass_status) ────
DO $$
DECLARE jid bigint;
BEGIN
  SELECT jobid INTO jid FROM cron.job WHERE command LIKE '%pass_status%' LIMIT 1;
  IF jid IS NOT NULL THEN
    PERFORM cron.alter_job(jid, command => $cron$
      UPDATE public.passes SET state = 'expired'::public.pass_state, updated_at = now()
      WHERE state = 'active' AND expires_at <= now();
    $cron$);
  END IF;
END $$;
