-- Treasury wallets (v2.48.0) — admin-managed list of on-chain destination wallets
-- for $1UP payments, so tournaments (and later the Pass) pick a wallet from a
-- dropdown instead of pasting an EVM address. Lives alongside bank_accounts on the
-- "Cuentas y Tesorerías" admin page. Consumers still store the chosen wallet's
-- ADDRESS (e.g. tournaments.treasury_address) — this table is the source list, so
-- the on-chain verification path is unchanged.
CREATE TABLE IF NOT EXISTS public.treasury_wallets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text    NOT NULL,
  address     text    NOT NULL,
  chain_id    integer NOT NULL DEFAULT 8453, -- Base mainnet
  is_active   boolean NOT NULL DEFAULT true,
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT treasury_wallets_address_evm CHECK (address ~ '^0x[a-fA-F0-9]{40}$')
);

-- Deny-all RLS: managed only via service-role admin routes (matches every other
-- admin/financial table).
ALTER TABLE public.treasury_wallets ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS treasury_wallets_active_idx
  ON public.treasury_wallets (is_active, sort_order);
